export const SITE = {
  name: "BHB Habitat",
  legal: "BHB Habitat",
  phone: "06 22 44 38 72",
  phoneTel: "tel:+33622443872",
  email: "bhb.habitat@gmail.com",
  address: "21 chemin de la Fitou Ouest",
  city: "La Tour du Crieu",
  zip: "09100",
  dept: "Ariège",
  deptNum: "09",
  region: "Occitanie",
  domain: "bhb-habitat09.fr",
  url: "https://www.bhb-habitat09.fr",
  siret: "",
  founded: 2008,
  experience: 17,
  chantiers: 300,
  guarantee: "10 ans",
  certifications: ["Garantie Décennale"],
  googleRating: 5.0,
  googleReviewCount: 6,
  googleMapsUrl: "https://maps.google.com/?q=La+Tour+du+Crieu+09100",
  hours: "Lun–Sam · 07h–19h",
  emergency: true,
  mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d46127.0!2d1.5!3d43.0!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12ae8d61af5b5c29%3A0x407a2b3aa5d5a40!2s09100%20La%20Tour%20du%20Crieu!5e0!3m2!1sfr!2sfr!4v1715000000000!5m2!1sfr!2sfr",
};

export const SERVICES = [
  {
    slug: "demoussage-traitement",
    title: "Démoussage & Traitement Hydrofuge",
    shortTitle: "Démoussage",
    emoji: "🧹",
    color: "#16A34A",
    urgency: false,
    headline: "Toiture propre, protégée 10 ans",
    description: "Nettoyage haute pression, démoussage complet, application d'hydrofuge garanti 10 ans. La solution la plus rentable pour allonger la durée de vie de votre toiture en Ariège.",
    benefits: ["Hydrofuge garanti 10 ans", "Élimine mousses et lichens", "Prix transparent, devis gratuit", "Résultats visibles immédiatement"],
    subServices: [
      { slug: "demoussage", title: "Démoussage Toiture", shortTitle: "Démoussage" },
      { slug: "traitement-hydrofuge", title: "Traitement Hydrofuge", shortTitle: "Hydrofuge" },
      { slug: "nettoyage-haute-pression", title: "Nettoyage Haute Pression", shortTitle: "Nettoyage HP" },
    ],
  },
  {
    slug: "couverture-toiture",
    title: "Couverture & Réfection de Toiture",
    shortTitle: "Couverture",
    emoji: "🏠",
    color: "#D4520A",
    urgency: true,
    headline: "Pose, réfection, rénovation — garantie décennale",
    description: "Pose neuve, réfection complète ou partielle de toiture. Tuiles canal, ardoises, tuiles béton. Artisan qualifié avec garantie décennale 10 ans en Ariège.",
    benefits: ["Garantie décennale 10 ans", "Tuiles canal, ardoises, béton", "Devis gratuit en 24h", "Artisan garanti décennale"],
    subServices: [
      { slug: "refection-toit", title: "Réfection de Toit", shortTitle: "Réfection" },
      { slug: "renovation-toiture", title: "Rénovation Toiture", shortTitle: "Rénovation" },
      { slug: "remplacement-tuiles", title: "Remplacement Tuiles", shortTitle: "Tuiles" },
      { slug: "pose-ardoises", title: "Pose d'Ardoises", shortTitle: "Ardoises" },
    ],
  },
  {
    slug: "charpente",
    title: "Charpente & Ossature Bois",
    shortTitle: "Charpente",
    emoji: "🪵",
    color: "#92400E",
    urgency: false,
    headline: "Pose, rénovation et traitement de charpente",
    description: "Charpente traditionnelle, industrielle ou ossature bois. Rénovation, renforcement, traitement insecticide contre les xylophages. Artisan couvreur-charpentier en Ariège.",
    benefits: ["Charpente traditionnelle & industrielle", "Traitement insecticide garanti", "Ossature bois sur mesure", "Expertise locale Ariège"],
    subServices: [
      { slug: "pose-charpente", title: "Pose de Charpente", shortTitle: "Pose charpente" },
      { slug: "renovation-charpente", title: "Rénovation Charpente", shortTitle: "Rénovation charpente" },
      { slug: "traitement-charpente", title: "Traitement Charpente", shortTitle: "Traitement" },
    ],
  },
  {
    slug: "etancheite",
    title: "Étanchéité & Toiture Terrasse",
    shortTitle: "Étanchéité",
    emoji: "💧",
    color: "#1D4ED8",
    urgency: true,
    headline: "Zéro infiltration, tranquillité garantie",
    description: "Étanchéité toiture terrasse, membrane EPDM, bitume élastomère. Traitement hydrofuge, réparation fuites. Intervention rapide en Ariège.",
    benefits: ["Membrane EPDM longue durée", "Réparation fuites urgente", "Toiture terrasse & plate", "Intervention sous 48h"],
    subServices: [
      { slug: "etancheite-terrasse", title: "Étanchéité Terrasse", shortTitle: "Terrasse" },
      { slug: "reparation-fuite", title: "Réparation Fuite Toiture", shortTitle: "Réparation fuite" },
      { slug: "membrane-epdm", title: "Membrane EPDM", shortTitle: "EPDM" },
    ],
  },
  {
    slug: "zinguerie",
    title: "Zinguerie & Accessoires",
    shortTitle: "Zinguerie",
    emoji: "🔩",
    color: "#475569",
    urgency: false,
    headline: "Noues, gouttières, faîtages en zinc",
    description: "Pose et rénovation de gouttières, noues, faîtages, chéneaux. Zinc, aluminium, cuivre. Artisan zingueur qualifié en Ariège.",
    benefits: ["Zinc, alu, cuivre", "Gouttières & chéneaux", "Noues & faîtages", "Joints de dilatation"],
    subServices: [
      { slug: "gouttieres", title: "Gouttières", shortTitle: "Gouttières" },
      { slug: "noues-faitage", title: "Noues & Faîtages", shortTitle: "Noues & faîtage" },
    ],
  },
  {
    slug: "urgence-toiture",
    title: "Urgence Toiture",
    shortTitle: "Urgence",
    emoji: "🚨",
    color: "#EF4444",
    urgency: true,
    headline: "Fuite, tempête, tuiles cassées — 48h",
    description: "Intervention d'urgence en Ariège : fuite toiture, tuiles arrachées par la tempête, dégâts des eaux. Disponible 7j/7. Devis gratuit sur place.",
    benefits: ["Intervention sous 48h", "Disponible 7j/7", "Devis gratuit sur place", "Prise en charge assurance"],
    subServices: [
      { slug: "fuite-toiture", title: "Fuite Toiture", shortTitle: "Fuite" },
      { slug: "tuiles-cassees", title: "Tuiles Cassées / Tempête", shortTitle: "Tuiles cassées" },
      { slug: "bachage-urgence", title: "Bâchage d'Urgence", shortTitle: "Bâchage" },
    ],
    href: "/urgence",
  },
];

export const ZONES = [
  { name: "Pamiers", slug: "pamiers", pop: "15 000" },
  { name: "Foix", slug: "foix", pop: "9 500", prefecture: true },
  { name: "Saverdun", slug: "saverdun", pop: "5 500" },
  { name: "Mirepoix", slug: "mirepoix", pop: "3 000" },
  { name: "La Tour du Crieu", slug: "la-tour-du-crieu", pop: "3 200", base: true },
  { name: "Varilhes", slug: "varilhes", pop: "2 800" },
  { name: "Lavelanet", slug: "lavelanet", pop: "6 000" },
  { name: "Tarascon-sur-Ariège", slug: "tarascon-sur-ariege", pop: "3 500" },
  { name: "Saint-Girons", slug: "saint-girons", pop: "6 500" },
  { name: "Ax-les-Thermes", slug: "ax-les-thermes", pop: "1 400" },
  { name: "Mazères", slug: "mazeres", pop: "3 000" },
  { name: "Lézat-sur-Lèze", slug: "lezat-sur-leze", pop: "2 100" },
];

export const REVIEWS = [
  {
    name: "Mandy Rozel",
    date: "Avril 2024",
    rating: 5,
    text: "Entreprise sérieuse qui m'a conseillé pour les travaux chez ma tante. Je vous le recommande.",
    service: "Couverture",
  },
  {
    name: "Alexandrine R.",
    date: "Janvier 2024",
    rating: 5,
    text: "On m'a conseillé cette entreprise — sérieux, à l'écoute, très gentil. Nous fait bien comprendre les choses. Je conseille.",
    service: "Démoussage",
  },
  {
    name: "Marine F.",
    date: "Janvier 2024",
    rating: 5,
    text: "Personne très sérieuse, vous pouvez vous y fier les yeux fermés. Très pro, travail propre et soigné. À l'écoute de vos demandes. Je recommande ++.",
    service: "Charpente",
  },
  {
    name: "Stéphane M.",
    date: "Janvier 2024",
    rating: 5,
    text: "Nous donne de très bons conseils, à l'écoute. Je recommande, je suis très content. Merci à l'équipe.",
    service: "Toiture",
  },
  {
    name: "Mika F.",
    date: "Janvier 2024",
    rating: 5,
    text: "Une personne courageuse, honnête et sérieuse ! Je suis très content de son travail. Je le recontacte dès que j'ai besoin.",
    service: "Étanchéité",
  },
  {
    name: "M. Cazeneuve",
    date: "Mars 2024",
    rating: 5,
    text: "Devis rapide, intervention propre et efficace. Résultat parfait. Jason est un vrai professionnel, je recommande sans hésitation.",
    service: "Démoussage",
  },
];

export const FAQS = [
  {
    q: "Quel est le prix d'un démoussage de toiture en Ariège ?",
    a: "Le prix d'un démoussage en Ariège varie entre 15 et 35 €/m² selon la superficie, l'inclinaison et l'état de la toiture. Pour une maison standard de 80 m² de toiture, comptez entre 1 200 et 2 800 €. Nous réalisons un devis gratuit et personnalisé après diagnostic sur place.",
  },
  {
    q: "Combien de temps dure un traitement hydrofuge ?",
    a: "Notre traitement hydrofuge est garanti 10 ans. Il protège vos tuiles contre l'humidité, les mousses, lichens et les variations thermiques du climat ariégeois. Appliqué après démoussage, il imperméabilise la surface et prolonge la durée de vie de votre toiture de 10 à 20 ans.",
  },
  {
    q: "Intervenez-vous en urgence pour les fuites de toiture ?",
    a: "Oui, nous intervenons pour les urgences (fuite, tuiles cassées, dégâts tempête) sous 24 à 48h dans tout l'Ariège, 7j/7. Appelez directement le 06 16 75 97 51 pour une prise en charge rapide.",
  },
  {
    q: "Êtes-vous assurés ? Puis-je bénéficier d'aides de l'État ?",
    a: "Oui, nous sommes couverts par une garantie décennale 10 ans sur tous nos travaux. Vous pouvez également bénéficier de MaPrimeRénov', l'Éco-PTZ et la TVA réduite à 5,5% pour vos travaux de rénovation.",
  },
  {
    q: "Dans quelles communes de l'Ariège intervenez-vous ?",
    a: "Nous intervenons dans tout le département 09 : Pamiers, Foix, Saverdun, La Tour du Crieu, Mirepoix, Lavelanet, Tarascon-sur-Ariège, Saint-Girons, Ax-les-Thermes, Varilhes, Mazères, et toutes les communes environnantes. Déplacement gratuit pour le devis.",
  },
  {
    q: "Quelle garantie proposez-vous sur vos travaux ?",
    a: "Tous nos travaux de couverture bénéficient de la garantie décennale obligatoire (10 ans). Le traitement hydrofuge est garanti 10 ans. Nous sommes également assurés en responsabilité civile professionnelle. Vous êtes protégé.",
  },
  {
    q: "Comment se passe le devis ?",
    a: "Simple : vous nous appelez ou remplissez le formulaire en ligne. Nous vous contactons sous 24h pour planifier un diagnostic gratuit chez vous. Sur place, nous évaluons l'état de la toiture et vous remettons un devis détaillé, transparent, sans engagement.",
  },
];
